// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_household_transmission_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 121> locations_array__ =
  {" (found before start of program)",
  " (in 'household_transmission', line 28, column 2 to column 34)",
  " (in 'household_transmission', line 29, column 2 to column 36)",
  " (in 'household_transmission', line 30, column 2 to column 17)",
  " (in 'household_transmission', line 31, column 2 to column 17)",
  " (in 'household_transmission', line 32, column 2 to column 17)",
  " (in 'household_transmission', line 33, column 2 to column 17)",
  " (in 'household_transmission', line 34, column 2 to column 34)",
  " (in 'household_transmission', line 35, column 2 to column 34)",
  " (in 'household_transmission', line 38, column 2 to column 33)",
  " (in 'household_transmission', line 39, column 2 to column 35)",
  " (in 'household_transmission', line 40, column 2 to column 39)",
  " (in 'household_transmission', line 41, column 2 to column 39)",
  " (in 'household_transmission', line 42, column 2 to column 54)",
  " (in 'household_transmission', line 43, column 2 to column 54)",
  " (in 'household_transmission', line 44, column 2 to column 33)",
  " (in 'household_transmission', line 45, column 17 to column 80)",
  " (in 'household_transmission', line 45, column 2 to column 80)",
  " (in 'household_transmission', line 46, column 2 to column 37)",
  " (in 'household_transmission', line 47, column 17 to column 86)",
  " (in 'household_transmission', line 47, column 2 to column 86)",
  " (in 'household_transmission', line 51, column 2 to column 39)",
  " (in 'household_transmission', line 52, column 2 to column 41)",
  " (in 'household_transmission', line 53, column 2 to column 28)",
  " (in 'household_transmission', line 54, column 2 to column 28)",
  " (in 'household_transmission', line 55, column 2 to column 29)",
  " (in 'household_transmission', line 56, column 2 to column 29)",
  " (in 'household_transmission', line 62, column 4 to column 25)",
  " (in 'household_transmission', line 63, column 4 to column 27)",
  " (in 'household_transmission', line 60, column 9 to line 64, column 3)",
  " (in 'household_transmission', line 58, column 4 to column 25)",
  " (in 'household_transmission', line 59, column 4 to column 27)",
  " (in 'household_transmission', line 57, column 24 to line 60, column 3)",
  " (in 'household_transmission', line 57, column 2 to line 64, column 3)",
  " (in 'household_transmission', line 68, column 4 to column 27)",
  " (in 'household_transmission', line 70, column 7 to column 35)",
  " (in 'household_transmission', line 69, column 44 to line 71, column 5)",
  " (in 'household_transmission', line 69, column 4 to line 71, column 5)",
  " (in 'household_transmission', line 72, column 4 to column 55)",
  " (in 'household_transmission', line 75, column 8 to column 26)",
  " (in 'household_transmission', line 76, column 8 to column 83)",
  " (in 'household_transmission', line 77, column 8 to column 25)",
  " (in 'household_transmission', line 78, column 8 to column 62)",
  " (in 'household_transmission', line 80, column 10 to column 39)",
  " (in 'household_transmission', line 81, column 32 to column 41)",
  " (in 'household_transmission', line 81, column 10 to column 41)",
  " (in 'household_transmission', line 82, column 10 to column 47)",
  " (in 'household_transmission', line 83, column 23 to column 32)",
  " (in 'household_transmission', line 83, column 10 to column 32)",
  " (in 'household_transmission', line 85, column 10 to column 32)",
  " (in 'household_transmission', line 87, column 13 to column 40)",
  " (in 'household_transmission', line 86, column 49 to line 88, column 11)",
  " (in 'household_transmission', line 86, column 10 to line 88, column 11)",
  " (in 'household_transmission', line 89, column 10 to column 64)",
  " (in 'household_transmission', line 91, column 10 to column 27)",
  " (in 'household_transmission', line 96, column 16 to column 26)",
  " (in 'household_transmission', line 94, column 16 to column 43)",
  " (in 'household_transmission', line 93, column 13 to line 96, column 26)",
  " (in 'household_transmission', line 92, column 36 to line 97, column 11)",
  " (in 'household_transmission', line 92, column 10 to line 97, column 11)",
  " (in 'household_transmission', line 98, column 10 to column 37)",
  " (in 'household_transmission', line 100, column 10 to column 27)",
  " (in 'household_transmission', line 102, column 13 to column 38)",
  " (in 'household_transmission', line 103, column 28 to column 70)",
  " (in 'household_transmission', line 103, column 13 to column 70)",
  " (in 'household_transmission', line 101, column 32 to line 104, column 11)",
  " (in 'household_transmission', line 101, column 10 to line 104, column 11)",
  " (in 'household_transmission', line 105, column 10 to column 60)",
  " (in 'household_transmission', line 106, column 10 to column 33)",
  " (in 'household_transmission', line 79, column 36 to line 107, column 9)",
  " (in 'household_transmission', line 79, column 8 to line 107, column 9)",
  " (in 'household_transmission', line 108, column 8 to column 48)",
  " (in 'household_transmission', line 109, column 8 to column 61)",
  " (in 'household_transmission', line 74, column 45 to line 110, column 7)",
  " (in 'household_transmission', line 74, column 6 to line 110, column 7)",
  " (in 'household_transmission', line 73, column 19 to line 111, column 5)",
  " (in 'household_transmission', line 73, column 4 to line 111, column 5)",
  " (in 'household_transmission', line 66, column 17 to line 112, column 3)",
  " (in 'household_transmission', line 66, column 2 to line 112, column 3)",
  " (in 'household_transmission', line 2, column 2 to column 17)",
  " (in 'household_transmission', line 3, column 2 to column 17)",
  " (in 'household_transmission', line 4, column 2 to column 17)",
  " (in 'household_transmission', line 5, column 2 to column 17)",
  " (in 'household_transmission', line 6, column 2 to column 13)",
  " (in 'household_transmission', line 8, column 2 to column 36)",
  " (in 'household_transmission', line 9, column 2 to column 36)",
  " (in 'household_transmission', line 10, column 2 to column 35)",
  " (in 'household_transmission', line 11, column 2 to column 40)",
  " (in 'household_transmission', line 12, column 30 to column 31)",
  " (in 'household_transmission', line 12, column 2 to column 33)",
  " (in 'household_transmission', line 13, column 32 to column 33)",
  " (in 'household_transmission', line 13, column 2 to column 35)",
  " (in 'household_transmission', line 14, column 26 to column 27)",
  " (in 'household_transmission', line 14, column 29 to column 30)",
  " (in 'household_transmission', line 14, column 2 to column 32)",
  " (in 'household_transmission', line 15, column 37 to column 38)",
  " (in 'household_transmission', line 15, column 40 to column 41)",
  " (in 'household_transmission', line 15, column 2 to column 43)",
  " (in 'household_transmission', line 16, column 13 to column 14)",
  " (in 'household_transmission', line 16, column 16 to column 17)",
  " (in 'household_transmission', line 16, column 2 to column 19)",
  " (in 'household_transmission', line 17, column 31 to column 32)",
  " (in 'household_transmission', line 17, column 2 to column 34)",
  " (in 'household_transmission', line 18, column 2 to column 35)",
  " (in 'household_transmission', line 19, column 23 to column 24)",
  " (in 'household_transmission', line 19, column 2 to column 26)",
  " (in 'household_transmission', line 20, column 2 to column 27)",
  " (in 'household_transmission', line 21, column 26 to column 27)",
  " (in 'household_transmission', line 21, column 29 to column 40)",
  " (in 'household_transmission', line 21, column 2 to column 42)",
  " (in 'household_transmission', line 22, column 2 to column 30)",
  " (in 'household_transmission', line 23, column 2 to column 32)",
  " (in 'household_transmission', line 24, column 9 to column 10)",
  " (in 'household_transmission', line 24, column 12 to column 13)",
  " (in 'household_transmission', line 24, column 2 to column 36)",
  " (in 'household_transmission', line 25, column 9 to column 10)",
  " (in 'household_transmission', line 25, column 2 to column 22)",
  " (in 'household_transmission', line 28, column 9 to column 12)",
  " (in 'household_transmission', line 29, column 9 to column 12)",
  " (in 'household_transmission', line 38, column 18 to column 19)",
  " (in 'household_transmission', line 39, column 18 to column 19)"};
#include <stan_meta_header.hpp>
class model_household_transmission final : public model_base_crtp<model_household_transmission> {
private:
  int N;
  int T;
  int H;
  int R;
  double delta;
  int use_vl_data;
  int use_ab_susc;
  int use_ab_inf;
  int use_curve_logic;
  std::vector<int> hh_id;
  std::vector<int> role_id;
  std::vector<std::vector<int>> I;
  std::vector<std::vector<int>> time_since_infection;
  std::vector<std::vector<double>> V_raw;
  std::vector<int> has_ab;
  double alpha_comm_by_role;
  std::vector<int> hh_size;
  int hh_max_size;
  std::vector<std::vector<int>> hh_members;
  double reference_phi;
  double reference_kappa;
  Eigen::Matrix<double,-1,-1> seasonal_forcing_mat_data__;
  Eigen::Matrix<double,-1,1> g_profile_data__;
  int log_phi_by_role_raw_1dim__;
  int log_kappa_by_role_raw_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> seasonal_forcing_mat{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> g_profile{nullptr, 0};
public:
  ~model_household_transmission() {}
  model_household_transmission(stan::io::var_context& context__, unsigned int
                               random_seed__ = 0, std::ostream*
                               pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_household_transmission_namespace::model_household_transmission";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 79;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 79;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 79;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 80;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 80;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 80;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 81;
      context__.validate_dims("data initialization", "H", "int",
        std::vector<size_t>{});
      H = std::numeric_limits<int>::min();
      current_statement__ = 81;
      H = context__.vals_i("H")[(1 - 1)];
      current_statement__ = 81;
      stan::math::check_greater_or_equal(function__, "H", H, 1);
      current_statement__ = 82;
      context__.validate_dims("data initialization", "R", "int",
        std::vector<size_t>{});
      R = std::numeric_limits<int>::min();
      current_statement__ = 82;
      R = context__.vals_i("R")[(1 - 1)];
      current_statement__ = 82;
      stan::math::check_greater_or_equal(function__, "R", R, 1);
      current_statement__ = 83;
      context__.validate_dims("data initialization", "delta", "double",
        std::vector<size_t>{});
      delta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 83;
      delta = context__.vals_r("delta")[(1 - 1)];
      current_statement__ = 84;
      context__.validate_dims("data initialization", "use_vl_data", "int",
        std::vector<size_t>{});
      use_vl_data = std::numeric_limits<int>::min();
      current_statement__ = 84;
      use_vl_data = context__.vals_i("use_vl_data")[(1 - 1)];
      current_statement__ = 84;
      stan::math::check_greater_or_equal(function__, "use_vl_data",
        use_vl_data, 0);
      current_statement__ = 84;
      stan::math::check_less_or_equal(function__, "use_vl_data", use_vl_data,
        1);
      current_statement__ = 85;
      context__.validate_dims("data initialization", "use_ab_susc", "int",
        std::vector<size_t>{});
      use_ab_susc = std::numeric_limits<int>::min();
      current_statement__ = 85;
      use_ab_susc = context__.vals_i("use_ab_susc")[(1 - 1)];
      current_statement__ = 85;
      stan::math::check_greater_or_equal(function__, "use_ab_susc",
        use_ab_susc, 0);
      current_statement__ = 85;
      stan::math::check_less_or_equal(function__, "use_ab_susc", use_ab_susc,
        1);
      current_statement__ = 86;
      context__.validate_dims("data initialization", "use_ab_inf", "int",
        std::vector<size_t>{});
      use_ab_inf = std::numeric_limits<int>::min();
      current_statement__ = 86;
      use_ab_inf = context__.vals_i("use_ab_inf")[(1 - 1)];
      current_statement__ = 86;
      stan::math::check_greater_or_equal(function__, "use_ab_inf",
        use_ab_inf, 0);
      current_statement__ = 86;
      stan::math::check_less_or_equal(function__, "use_ab_inf", use_ab_inf, 1);
      current_statement__ = 87;
      context__.validate_dims("data initialization", "use_curve_logic",
        "int", std::vector<size_t>{});
      use_curve_logic = std::numeric_limits<int>::min();
      current_statement__ = 87;
      use_curve_logic = context__.vals_i("use_curve_logic")[(1 - 1)];
      current_statement__ = 87;
      stan::math::check_greater_or_equal(function__, "use_curve_logic",
        use_curve_logic, 0);
      current_statement__ = 87;
      stan::math::check_less_or_equal(function__, "use_curve_logic",
        use_curve_logic, 1);
      current_statement__ = 88;
      stan::math::validate_non_negative_index("hh_id", "N", N);
      current_statement__ = 89;
      context__.validate_dims("data initialization", "hh_id", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      hh_id = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 89;
      hh_id = context__.vals_i("hh_id");
      current_statement__ = 89;
      stan::math::check_greater_or_equal(function__, "hh_id", hh_id, 1);
      current_statement__ = 89;
      stan::math::check_less_or_equal(function__, "hh_id", hh_id, H);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("role_id", "N", N);
      current_statement__ = 91;
      context__.validate_dims("data initialization", "role_id", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      role_id = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 91;
      role_id = context__.vals_i("role_id");
      current_statement__ = 91;
      stan::math::check_greater_or_equal(function__, "role_id", role_id, 1);
      current_statement__ = 91;
      stan::math::check_less_or_equal(function__, "role_id", role_id, R);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("I", "N", N);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("I", "T", T);
      current_statement__ = 94;
      context__.validate_dims("data initialization", "I", "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(T)});
      I = std::vector<std::vector<int>>(N,
            std::vector<int>(T, std::numeric_limits<int>::min()));
      {
        std::vector<int> I_flat__;
        current_statement__ = 94;
        I_flat__ = context__.vals_i("I");
        current_statement__ = 94;
        pos__ = 1;
        current_statement__ = 94;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 94;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 94;
            stan::model::assign(I, I_flat__[(pos__ - 1)],
              "assigning variable I", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 94;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 94;
      stan::math::check_greater_or_equal(function__, "I", I, 0);
      current_statement__ = 94;
      stan::math::check_less_or_equal(function__, "I", I, 1);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("time_since_infection", "N", N);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("time_since_infection", "T", T);
      current_statement__ = 97;
      context__.validate_dims("data initialization", "time_since_infection",
        "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(T)});
      time_since_infection = std::vector<std::vector<int>>(N,
                               std::vector<int>(T,
                                 std::numeric_limits<int>::min()));
      {
        std::vector<int> time_since_infection_flat__;
        current_statement__ = 97;
        time_since_infection_flat__ = context__.vals_i("time_since_infection");
        current_statement__ = 97;
        pos__ = 1;
        current_statement__ = 97;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 97;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 97;
            stan::model::assign(time_since_infection,
              time_since_infection_flat__[(pos__ - 1)],
              "assigning variable time_since_infection",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 97;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 97;
      stan::math::check_greater_or_equal(function__, "time_since_infection",
        time_since_infection, -1);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("V_raw", "N", N);
      current_statement__ = 99;
      stan::math::validate_non_negative_index("V_raw", "T", T);
      current_statement__ = 100;
      context__.validate_dims("data initialization", "V_raw", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(T)});
      V_raw = std::vector<std::vector<double>>(N,
                std::vector<double>(T,
                  std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> V_raw_flat__;
        current_statement__ = 100;
        V_raw_flat__ = context__.vals_r("V_raw");
        current_statement__ = 100;
        pos__ = 1;
        current_statement__ = 100;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 100;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 100;
            stan::model::assign(V_raw, V_raw_flat__[(pos__ - 1)],
              "assigning variable V_raw", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 100;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 101;
      stan::math::validate_non_negative_index("has_ab", "N", N);
      current_statement__ = 102;
      context__.validate_dims("data initialization", "has_ab", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      has_ab = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 102;
      has_ab = context__.vals_i("has_ab");
      current_statement__ = 102;
      stan::math::check_greater_or_equal(function__, "has_ab", has_ab, 0);
      current_statement__ = 102;
      stan::math::check_less_or_equal(function__, "has_ab", has_ab, 1);
      current_statement__ = 103;
      context__.validate_dims("data initialization", "alpha_comm_by_role",
        "double", std::vector<size_t>{});
      alpha_comm_by_role = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 103;
      alpha_comm_by_role = context__.vals_r("alpha_comm_by_role")[(1 - 1)];
      current_statement__ = 103;
      stan::math::check_greater_or_equal(function__, "alpha_comm_by_role",
        alpha_comm_by_role, 0);
      current_statement__ = 104;
      stan::math::validate_non_negative_index("hh_size", "H", H);
      current_statement__ = 105;
      context__.validate_dims("data initialization", "hh_size", "int",
        std::vector<size_t>{static_cast<size_t>(H)});
      hh_size = std::vector<int>(H, std::numeric_limits<int>::min());
      current_statement__ = 105;
      hh_size = context__.vals_i("hh_size");
      current_statement__ = 105;
      stan::math::check_greater_or_equal(function__, "hh_size", hh_size, 1);
      current_statement__ = 106;
      context__.validate_dims("data initialization", "hh_max_size", "int",
        std::vector<size_t>{});
      hh_max_size = std::numeric_limits<int>::min();
      current_statement__ = 106;
      hh_max_size = context__.vals_i("hh_max_size")[(1 - 1)];
      current_statement__ = 106;
      stan::math::check_greater_or_equal(function__, "hh_max_size",
        hh_max_size, 1);
      current_statement__ = 107;
      stan::math::validate_non_negative_index("hh_members", "H", H);
      current_statement__ = 108;
      stan::math::validate_non_negative_index("hh_members", "hh_max_size",
        hh_max_size);
      current_statement__ = 109;
      context__.validate_dims("data initialization", "hh_members", "int",
        std::vector<size_t>{static_cast<size_t>(H),
          static_cast<size_t>(hh_max_size)});
      hh_members = std::vector<std::vector<int>>(H,
                     std::vector<int>(hh_max_size,
                       std::numeric_limits<int>::min()));
      {
        std::vector<int> hh_members_flat__;
        current_statement__ = 109;
        hh_members_flat__ = context__.vals_i("hh_members");
        current_statement__ = 109;
        pos__ = 1;
        current_statement__ = 109;
        for (int sym1__ = 1; sym1__ <= hh_max_size; ++sym1__) {
          current_statement__ = 109;
          for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
            current_statement__ = 109;
            stan::model::assign(hh_members, hh_members_flat__[(pos__ - 1)],
              "assigning variable hh_members",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 109;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 109;
      stan::math::check_greater_or_equal(function__, "hh_members",
        hh_members, 0);
      current_statement__ = 110;
      context__.validate_dims("data initialization", "reference_phi",
        "double", std::vector<size_t>{});
      reference_phi = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 110;
      reference_phi = context__.vals_r("reference_phi")[(1 - 1)];
      current_statement__ = 110;
      stan::math::check_greater_or_equal(function__, "reference_phi",
        reference_phi, 0);
      current_statement__ = 111;
      context__.validate_dims("data initialization", "reference_kappa",
        "double", std::vector<size_t>{});
      reference_kappa = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 111;
      reference_kappa = context__.vals_r("reference_kappa")[(1 - 1)];
      current_statement__ = 111;
      stan::math::check_greater_or_equal(function__, "reference_kappa",
        reference_kappa, 0);
      current_statement__ = 112;
      stan::math::validate_non_negative_index("seasonal_forcing_mat", "T", T);
      current_statement__ = 113;
      stan::math::validate_non_negative_index("seasonal_forcing_mat", "R", R);
      current_statement__ = 114;
      context__.validate_dims("data initialization", "seasonal_forcing_mat",
        "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(R)});
      seasonal_forcing_mat_data__ = Eigen::Matrix<double,-1,-1>::Constant(T,
                                      R,
                                      std::numeric_limits<double>::quiet_NaN());
      new (&seasonal_forcing_mat)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(seasonal_forcing_mat_data__.data(),
        T, R);
      {
        std::vector<local_scalar_t__> seasonal_forcing_mat_flat__;
        current_statement__ = 114;
        seasonal_forcing_mat_flat__ = context__.vals_r("seasonal_forcing_mat");
        current_statement__ = 114;
        pos__ = 1;
        current_statement__ = 114;
        for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
          current_statement__ = 114;
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            current_statement__ = 114;
            stan::model::assign(seasonal_forcing_mat,
              seasonal_forcing_mat_flat__[(pos__ - 1)],
              "assigning variable seasonal_forcing_mat",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 114;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 115;
      stan::math::validate_non_negative_index("g_profile", "T", T);
      current_statement__ = 116;
      context__.validate_dims("data initialization", "g_profile", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      g_profile_data__ = Eigen::Matrix<double,-1,1>::Constant(T,
                           std::numeric_limits<double>::quiet_NaN());
      new (&g_profile)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(g_profile_data__.data(), T);
      {
        std::vector<local_scalar_t__> g_profile_flat__;
        current_statement__ = 116;
        g_profile_flat__ = context__.vals_r("g_profile");
        current_statement__ = 116;
        pos__ = 1;
        current_statement__ = 116;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 116;
          stan::model::assign(g_profile, g_profile_flat__[(pos__ - 1)],
            "assigning variable g_profile", stan::model::index_uni(sym1__));
          current_statement__ = 116;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 117;
      log_phi_by_role_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 117;
      log_phi_by_role_raw_1dim__ = (R - 1);
      current_statement__ = 117;
      stan::math::validate_non_negative_index("log_phi_by_role_raw", "R - 1",
        log_phi_by_role_raw_1dim__);
      current_statement__ = 118;
      log_kappa_by_role_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 118;
      log_kappa_by_role_raw_1dim__ = (R - 1);
      current_statement__ = 118;
      stan::math::validate_non_negative_index("log_kappa_by_role_raw",
        "R - 1", log_kappa_by_role_raw_1dim__);
      current_statement__ = 119;
      stan::math::validate_non_negative_index("phi_by_role", "R", R);
      current_statement__ = 120;
      stan::math::validate_non_negative_index("kappa_by_role", "R", R);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = log_phi_by_role_raw_1dim__ +
      log_kappa_by_role_raw_1dim__ + 1 + 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_household_transmission";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_household_transmission_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> log_phi_by_role_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(log_phi_by_role_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      log_phi_by_role_raw = in__.template read<
                              Eigen::Matrix<local_scalar_t__,-1,1>>(log_phi_by_role_raw_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> log_kappa_by_role_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(log_kappa_by_role_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 2;
      log_kappa_by_role_raw = in__.template read<
                                Eigen::Matrix<local_scalar_t__,-1,1>>(log_kappa_by_role_raw_1dim__);
      local_scalar_t__ log_beta1 = DUMMY_VAR__;
      current_statement__ = 3;
      log_beta1 = in__.template read<local_scalar_t__>();
      local_scalar_t__ log_beta2 = DUMMY_VAR__;
      current_statement__ = 4;
      log_beta2 = in__.template read<local_scalar_t__>();
      local_scalar_t__ log_beta3 = DUMMY_VAR__;
      current_statement__ = 5;
      log_beta3 = in__.template read<local_scalar_t__>();
      local_scalar_t__ log_beta4 = DUMMY_VAR__;
      current_statement__ = 6;
      log_beta4 = in__.template read<local_scalar_t__>();
      local_scalar_t__ V_ref = DUMMY_VAR__;
      current_statement__ = 7;
      V_ref = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0.1, 10, lp__);
      local_scalar_t__ V_rho = DUMMY_VAR__;
      current_statement__ = 8;
      V_rho = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0.1, 10, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> phi_by_role =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(R, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> kappa_by_role =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(R, DUMMY_VAR__);
      local_scalar_t__ beta1 = DUMMY_VAR__;
      current_statement__ = 11;
      beta1 = stan::math::exp(log_beta1);
      local_scalar_t__ beta2 = DUMMY_VAR__;
      current_statement__ = 12;
      beta2 = stan::math::exp(log_beta2);
      local_scalar_t__ beta3 = DUMMY_VAR__;
      current_statement__ = 13;
      beta3 = stan::math::inv_logit(log_beta3);
      local_scalar_t__ beta4 = DUMMY_VAR__;
      current_statement__ = 14;
      beta4 = stan::math::inv_logit(log_beta4);
      current_statement__ = 15;
      stan::model::assign(phi_by_role, reference_phi,
        "assigning variable phi_by_role", stan::model::index_uni(1));
      current_statement__ = 17;
      for (int r = 2; r <= R; ++r) {
        current_statement__ = 16;
        stan::model::assign(phi_by_role, (reference_phi *
          stan::math::exp(
            stan::model::rvalue(log_phi_by_role_raw, "log_phi_by_role_raw",
              stan::model::index_uni((r - 1))))),
          "assigning variable phi_by_role", stan::model::index_uni(r));
      }
      current_statement__ = 18;
      stan::model::assign(kappa_by_role, reference_kappa,
        "assigning variable kappa_by_role", stan::model::index_uni(1));
      current_statement__ = 20;
      for (int r = 2; r <= R; ++r) {
        current_statement__ = 19;
        stan::model::assign(kappa_by_role, (reference_kappa *
          stan::math::exp(
            stan::model::rvalue(log_kappa_by_role_raw,
              "log_kappa_by_role_raw", stan::model::index_uni((r - 1))))),
          "assigning variable kappa_by_role", stan::model::index_uni(r));
      }
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "phi_by_role",
        phi_by_role, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "kappa_by_role",
        kappa_by_role, 0);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "beta1", beta1, 0);
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "beta2", beta2, 0);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "beta3", beta3, 0);
      current_statement__ = 13;
      stan::math::check_less_or_equal(function__, "beta3", beta3, 1);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "beta4", beta4, 0);
      current_statement__ = 14;
      stan::math::check_less_or_equal(function__, "beta4", beta4, 1);
      {
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_phi_by_role_raw,
                         0, 0.5));
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         log_kappa_by_role_raw, 0, 0.5));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_beta1, -6, 1));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_beta2, -6, 1));
        current_statement__ = 25;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_beta3, 0, 1.5));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_beta4, 0, 1.5));
        current_statement__ = 33;
        if (stan::math::logical_eq(use_vl_data, 1)) {
          current_statement__ = 30;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(V_ref, 3, 1));
          current_statement__ = 31;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(V_rho, 2.5, 1));
        } else {
          current_statement__ = 27;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(V_ref, 3, 2));
          current_statement__ = 28;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(V_rho, 2.5, 2));
        }
        current_statement__ = 78;
        for (int n = 1; n <= N; ++n) {
          local_scalar_t__ susc_effect = DUMMY_VAR__;
          current_statement__ = 34;
          susc_effect = 1.0;
          current_statement__ = 37;
          if ((stan::math::primitive_value(
                 stan::math::logical_eq(use_ab_susc, 1))
              &&
              stan::math::primitive_value(
                stan::math::logical_eq(
                  stan::model::rvalue(has_ab, "has_ab",
                    stan::model::index_uni(n)), 1)))) {
            current_statement__ = 35;
            susc_effect = (1.0 - beta3);
          }
          local_scalar_t__ phi_n = DUMMY_VAR__;
          current_statement__ = 38;
          phi_n = (susc_effect *
            stan::model::rvalue(phi_by_role, "phi_by_role",
              stan::model::index_uni(
                stan::model::rvalue(role_id, "role_id",
                  stan::model::index_uni(n)))));
          current_statement__ = 76;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 74;
            if ((stan::math::primitive_value(stan::math::logical_eq(t, 1)) ||
                stan::math::primitive_value(
                  stan::math::logical_eq(
                    stan::math::sum(
                      stan::model::rvalue(I, "I", stan::model::index_uni(n),
                        stan::model::index_min_max(1, (t - 1)))), 0)))) {
              local_scalar_t__ lambda = DUMMY_VAR__;
              current_statement__ = 39;
              lambda = 0.0;
              current_statement__ = 40;
              lambda = (lambda + ((phi_n * alpha_comm_by_role) *
                stan::model::rvalue(seasonal_forcing_mat,
                  "seasonal_forcing_mat", stan::model::index_uni(t),
                  stan::model::index_uni(
                    stan::model::rvalue(role_id, "role_id",
                      stan::model::index_uni(n))))));
              int h = std::numeric_limits<int>::min();
              current_statement__ = 41;
              h = stan::model::rvalue(hh_id, "hh_id",
                    stan::model::index_uni(n));
              local_scalar_t__ scaling_h = DUMMY_VAR__;
              current_statement__ = 42;
              scaling_h = stan::math::pow((1.0 /
                            stan::math::max(
                              stan::model::rvalue(hh_size, "hh_size",
                                stan::model::index_uni(h)), 1)), delta);
              current_statement__ = 70;
              for (int m_idx = 1; m_idx <=
                   stan::model::rvalue(hh_size, "hh_size",
                     stan::model::index_uni(h)); ++m_idx) {
                int m = std::numeric_limits<int>::min();
                current_statement__ = 43;
                m = stan::model::rvalue(hh_members, "hh_members",
                      stan::model::index_uni(h),
                      stan::model::index_uni(m_idx));
                current_statement__ = 45;
                if ((stan::math::primitive_value(stan::math::logical_eq(m, 0))
                    ||
                    stan::math::primitive_value(stan::math::logical_eq(m, n)))) {
                  continue;
                }
                int tau = std::numeric_limits<int>::min();
                current_statement__ = 46;
                tau = stan::model::rvalue(time_since_infection,
                        "time_since_infection", stan::model::index_uni(m),
                        stan::model::index_uni(t));
                current_statement__ = 48;
                if (stan::math::logical_lt(tau, 0)) {
                  continue;
                }
                local_scalar_t__ inf_effect = DUMMY_VAR__;
                current_statement__ = 49;
                inf_effect = 1.0;
                current_statement__ = 52;
                if ((stan::math::primitive_value(
                       stan::math::logical_eq(use_ab_inf, 1))
                    &&
                    stan::math::primitive_value(
                      stan::math::logical_eq(
                        stan::model::rvalue(has_ab, "has_ab",
                          stan::model::index_uni(m)), 1)))) {
                  current_statement__ = 50;
                  inf_effect = (1.0 - beta4);
                }
                local_scalar_t__ kappa_m = DUMMY_VAR__;
                current_statement__ = 53;
                kappa_m = (inf_effect *
                  stan::model::rvalue(kappa_by_role, "kappa_by_role",
                    stan::model::index_uni(
                      stan::model::rvalue(role_id, "role_id",
                        stan::model::index_uni(m)))));
                local_scalar_t__ g_val = DUMMY_VAR__;
                current_statement__ = 54;
                g_val = 1.0;
                current_statement__ = 59;
                if (stan::math::logical_eq(use_curve_logic, 1)) {
                  current_statement__ = 57;
                  if (stan::math::logical_lte((tau + 1),
                        stan::math::num_elements(g_profile))) {
                    current_statement__ = 56;
                    g_val = stan::model::rvalue(g_profile, "g_profile",
                              stan::model::index_uni((tau + 1)));
                  } else {
                    current_statement__ = 55;
                    g_val = 0;
                  }
                }
                local_scalar_t__ term1 = DUMMY_VAR__;
                current_statement__ = 60;
                term1 = (beta1 * g_val);
                local_scalar_t__ term2 = DUMMY_VAR__;
                current_statement__ = 61;
                term2 = 0.0;
                current_statement__ = 66;
                if (stan::math::logical_eq(use_vl_data, 1)) {
                  local_scalar_t__ v_val = DUMMY_VAR__;
                  current_statement__ = 62;
                  v_val = stan::model::rvalue(V_raw, "V_raw",
                            stan::model::index_uni(m),
                            stan::model::index_uni(t));
                  current_statement__ = 64;
                  if (stan::math::logical_gt(v_val, 0)) {
                    current_statement__ = 63;
                    term2 = (beta2 *
                      stan::math::pow((v_val / V_ref), V_rho));
                  }
                }
                local_scalar_t__ h_mt = DUMMY_VAR__;
                current_statement__ = 67;
                h_mt = ((scaling_h * kappa_m) * (term1 + term2));
                current_statement__ = 68;
                lambda = (lambda + (phi_n * h_mt));
              }
              current_statement__ = 71;
              lambda = stan::math::fmin(stan::math::fmax(lambda, 1e-12), 1e6);
              current_statement__ = 72;
              lp_accum__.add(stan::math::bernoulli_lpmf<false>(
                               stan::model::rvalue(I, "I",
                                 stan::model::index_uni(n),
                                 stan::model::index_uni(t)), (1 -
                               stan::math::exp(-lambda))));
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_household_transmission_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> log_phi_by_role_raw =
        Eigen::Matrix<double,-1,1>::Constant(log_phi_by_role_raw_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      log_phi_by_role_raw = in__.template read<
                              Eigen::Matrix<local_scalar_t__,-1,1>>(log_phi_by_role_raw_1dim__);
      Eigen::Matrix<double,-1,1> log_kappa_by_role_raw =
        Eigen::Matrix<double,-1,1>::Constant(log_kappa_by_role_raw_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      log_kappa_by_role_raw = in__.template read<
                                Eigen::Matrix<local_scalar_t__,-1,1>>(log_kappa_by_role_raw_1dim__);
      double log_beta1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      log_beta1 = in__.template read<local_scalar_t__>();
      double log_beta2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      log_beta2 = in__.template read<local_scalar_t__>();
      double log_beta3 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      log_beta3 = in__.template read<local_scalar_t__>();
      double log_beta4 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      log_beta4 = in__.template read<local_scalar_t__>();
      double V_ref = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      V_ref = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0.1, 10, lp__);
      double V_rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      V_rho = in__.template read_constrain_lub<local_scalar_t__,
                jacobian__>(0.1, 10, lp__);
      Eigen::Matrix<double,-1,1> phi_by_role =
        Eigen::Matrix<double,-1,1>::Constant(R,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> kappa_by_role =
        Eigen::Matrix<double,-1,1>::Constant(R,
          std::numeric_limits<double>::quiet_NaN());
      double beta1 = std::numeric_limits<double>::quiet_NaN();
      double beta2 = std::numeric_limits<double>::quiet_NaN();
      double beta3 = std::numeric_limits<double>::quiet_NaN();
      double beta4 = std::numeric_limits<double>::quiet_NaN();
      out__.write(log_phi_by_role_raw);
      out__.write(log_kappa_by_role_raw);
      out__.write(log_beta1);
      out__.write(log_beta2);
      out__.write(log_beta3);
      out__.write(log_beta4);
      out__.write(V_ref);
      out__.write(V_rho);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 11;
      beta1 = stan::math::exp(log_beta1);
      current_statement__ = 12;
      beta2 = stan::math::exp(log_beta2);
      current_statement__ = 13;
      beta3 = stan::math::inv_logit(log_beta3);
      current_statement__ = 14;
      beta4 = stan::math::inv_logit(log_beta4);
      current_statement__ = 15;
      stan::model::assign(phi_by_role, reference_phi,
        "assigning variable phi_by_role", stan::model::index_uni(1));
      current_statement__ = 17;
      for (int r = 2; r <= R; ++r) {
        current_statement__ = 16;
        stan::model::assign(phi_by_role, (reference_phi *
          stan::math::exp(
            stan::model::rvalue(log_phi_by_role_raw, "log_phi_by_role_raw",
              stan::model::index_uni((r - 1))))),
          "assigning variable phi_by_role", stan::model::index_uni(r));
      }
      current_statement__ = 18;
      stan::model::assign(kappa_by_role, reference_kappa,
        "assigning variable kappa_by_role", stan::model::index_uni(1));
      current_statement__ = 20;
      for (int r = 2; r <= R; ++r) {
        current_statement__ = 19;
        stan::model::assign(kappa_by_role, (reference_kappa *
          stan::math::exp(
            stan::model::rvalue(log_kappa_by_role_raw,
              "log_kappa_by_role_raw", stan::model::index_uni((r - 1))))),
          "assigning variable kappa_by_role", stan::model::index_uni(r));
      }
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "phi_by_role",
        phi_by_role, 0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "kappa_by_role",
        kappa_by_role, 0);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "beta1", beta1, 0);
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "beta2", beta2, 0);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "beta3", beta3, 0);
      current_statement__ = 13;
      stan::math::check_less_or_equal(function__, "beta3", beta3, 1);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "beta4", beta4, 0);
      current_statement__ = 14;
      stan::math::check_less_or_equal(function__, "beta4", beta4, 1);
      if (emit_transformed_parameters__) {
        out__.write(phi_by_role);
        out__.write(kappa_by_role);
        out__.write(beta1);
        out__.write(beta2);
        out__.write(beta3);
        out__.write(beta4);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> log_phi_by_role_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(log_phi_by_role_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(log_phi_by_role_raw,
        in__.read<
          Eigen::Matrix<local_scalar_t__,-1,1>>(log_phi_by_role_raw_1dim__),
        "assigning variable log_phi_by_role_raw");
      out__.write(log_phi_by_role_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> log_kappa_by_role_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(log_kappa_by_role_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(log_kappa_by_role_raw,
        in__.read<
          Eigen::Matrix<local_scalar_t__,-1,1>>(log_kappa_by_role_raw_1dim__),
        "assigning variable log_kappa_by_role_raw");
      out__.write(log_kappa_by_role_raw);
      local_scalar_t__ log_beta1 = DUMMY_VAR__;
      current_statement__ = 3;
      log_beta1 = in__.read<local_scalar_t__>();
      out__.write(log_beta1);
      local_scalar_t__ log_beta2 = DUMMY_VAR__;
      current_statement__ = 4;
      log_beta2 = in__.read<local_scalar_t__>();
      out__.write(log_beta2);
      local_scalar_t__ log_beta3 = DUMMY_VAR__;
      current_statement__ = 5;
      log_beta3 = in__.read<local_scalar_t__>();
      out__.write(log_beta3);
      local_scalar_t__ log_beta4 = DUMMY_VAR__;
      current_statement__ = 6;
      log_beta4 = in__.read<local_scalar_t__>();
      out__.write(log_beta4);
      local_scalar_t__ V_ref = DUMMY_VAR__;
      current_statement__ = 7;
      V_ref = in__.read<local_scalar_t__>();
      out__.write_free_lub(0.1, 10, V_ref);
      local_scalar_t__ V_rho = DUMMY_VAR__;
      current_statement__ = 8;
      V_rho = in__.read<local_scalar_t__>();
      out__.write_free_lub(0.1, 10, V_rho);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization",
        "log_phi_by_role_raw", "double",
        std::vector<size_t>{static_cast<size_t>(log_phi_by_role_raw_1dim__)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization",
        "log_kappa_by_role_raw", "double",
        std::vector<size_t>{static_cast<size_t>(log_kappa_by_role_raw_1dim__)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "log_beta1",
        "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "log_beta2",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "log_beta3",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "log_beta4",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "V_ref", "double",
        std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "V_rho", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> log_phi_by_role_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(log_phi_by_role_raw_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> log_phi_by_role_raw_flat__;
        current_statement__ = 1;
        log_phi_by_role_raw_flat__ = context__.vals_r("log_phi_by_role_raw");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= log_phi_by_role_raw_1dim__; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(log_phi_by_role_raw,
            log_phi_by_role_raw_flat__[(pos__ - 1)],
            "assigning variable log_phi_by_role_raw",
            stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(log_phi_by_role_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> log_kappa_by_role_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(log_kappa_by_role_raw_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> log_kappa_by_role_raw_flat__;
        current_statement__ = 2;
        log_kappa_by_role_raw_flat__ = context__.vals_r("log_kappa_by_role_raw");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= log_kappa_by_role_raw_1dim__; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(log_kappa_by_role_raw,
            log_kappa_by_role_raw_flat__[(pos__ - 1)],
            "assigning variable log_kappa_by_role_raw",
            stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(log_kappa_by_role_raw);
      local_scalar_t__ log_beta1 = DUMMY_VAR__;
      current_statement__ = 3;
      log_beta1 = context__.vals_r("log_beta1")[(1 - 1)];
      out__.write(log_beta1);
      local_scalar_t__ log_beta2 = DUMMY_VAR__;
      current_statement__ = 4;
      log_beta2 = context__.vals_r("log_beta2")[(1 - 1)];
      out__.write(log_beta2);
      local_scalar_t__ log_beta3 = DUMMY_VAR__;
      current_statement__ = 5;
      log_beta3 = context__.vals_r("log_beta3")[(1 - 1)];
      out__.write(log_beta3);
      local_scalar_t__ log_beta4 = DUMMY_VAR__;
      current_statement__ = 6;
      log_beta4 = context__.vals_r("log_beta4")[(1 - 1)];
      out__.write(log_beta4);
      local_scalar_t__ V_ref = DUMMY_VAR__;
      current_statement__ = 7;
      V_ref = context__.vals_r("V_ref")[(1 - 1)];
      out__.write_free_lub(0.1, 10, V_ref);
      local_scalar_t__ V_rho = DUMMY_VAR__;
      current_statement__ = 8;
      V_rho = context__.vals_r("V_rho")[(1 - 1)];
      out__.write_free_lub(0.1, 10, V_rho);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"log_phi_by_role_raw",
                "log_kappa_by_role_raw", "log_beta1", "log_beta2",
                "log_beta3", "log_beta4", "V_ref", "V_rho"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"phi_by_role", "kappa_by_role", "beta1", "beta2", "beta3",
             "beta4"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    log_phi_by_role_raw_1dim__)},
                std::vector<size_t>{static_cast<size_t>(
                                      log_kappa_by_role_raw_1dim__)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(R)},
             std::vector<size_t>{static_cast<size_t>(R)},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= log_phi_by_role_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_phi_by_role_raw" + '.'
        + std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= log_kappa_by_role_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_kappa_by_role_raw" +
        '.' + std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "log_beta1");
    param_names__.emplace_back(std::string() + "log_beta2");
    param_names__.emplace_back(std::string() + "log_beta3");
    param_names__.emplace_back(std::string() + "log_beta4");
    param_names__.emplace_back(std::string() + "V_ref");
    param_names__.emplace_back(std::string() + "V_rho");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
        param_names__.emplace_back(std::string() + "phi_by_role" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
        param_names__.emplace_back(std::string() + "kappa_by_role" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "beta1");
      param_names__.emplace_back(std::string() + "beta2");
      param_names__.emplace_back(std::string() + "beta3");
      param_names__.emplace_back(std::string() + "beta4");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= log_phi_by_role_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_phi_by_role_raw" + '.'
        + std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= log_kappa_by_role_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "log_kappa_by_role_raw" +
        '.' + std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "log_beta1");
    param_names__.emplace_back(std::string() + "log_beta2");
    param_names__.emplace_back(std::string() + "log_beta3");
    param_names__.emplace_back(std::string() + "log_beta4");
    param_names__.emplace_back(std::string() + "V_ref");
    param_names__.emplace_back(std::string() + "V_rho");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
        param_names__.emplace_back(std::string() + "phi_by_role" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= R; ++sym1__) {
        param_names__.emplace_back(std::string() + "kappa_by_role" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "beta1");
      param_names__.emplace_back(std::string() + "beta2");
      param_names__.emplace_back(std::string() + "beta3");
      param_names__.emplace_back(std::string() + "beta4");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"log_phi_by_role_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_phi_by_role_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"log_kappa_by_role_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_kappa_by_role_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"log_beta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_beta2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_beta3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_beta4\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"V_ref\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"V_rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"phi_by_role\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(R) + "},\"block\":\"transformed_parameters\"},{\"name\":\"kappa_by_role\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(R) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta1\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta2\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta4\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"log_phi_by_role_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_phi_by_role_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"log_kappa_by_role_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_kappa_by_role_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"log_beta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_beta2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_beta3\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_beta4\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"V_ref\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"V_rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"phi_by_role\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(R) + "},\"block\":\"transformed_parameters\"},{\"name\":\"kappa_by_role\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(R) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta1\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta2\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta3\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta4\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((log_phi_by_role_raw_1dim__ +
      log_kappa_by_role_raw_1dim__) + 1) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((((R + R)
      + 1) + 1) + 1) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((log_phi_by_role_raw_1dim__ +
      log_kappa_by_role_raw_1dim__) + 1) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((((R + R)
      + 1) + 1) + 1) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_household_transmission_namespace::model_household_transmission;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_household_transmission_namespace::profiles__;
}
#endif
#endif
